# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-02-24 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0005_book_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(default='mysite/static/books/book.jpg', upload_to='mysite/static/books'),
        ),
    ]
