# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-02-24 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0006_auto_20180224_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(default='books/book.jpg', upload_to='books'),
        ),
    ]
