# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-02-24 15:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0007_auto_20180224_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='selling_cart',
            name='image',
            field=models.ImageField(default='books/book.jpg', upload_to='sellcart'),
        ),
        migrations.AddField(
            model_name='shopping_cart',
            name='image',
            field=models.ImageField(default='books/book.jpg', upload_to='shopcart'),
        ),
    ]
