# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-02-25 16:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0008_auto_20180224_1553'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('orderid', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=75)),
            ],
        ),
        migrations.RemoveField(
            model_name='book',
            name='id',
        ),
        migrations.RemoveField(
            model_name='selling_cart',
            name='author',
        ),
        migrations.RemoveField(
            model_name='selling_cart',
            name='image',
        ),
        migrations.RemoveField(
            model_name='selling_cart',
            name='isbn',
        ),
        migrations.RemoveField(
            model_name='selling_cart',
            name='price',
        ),
        migrations.RemoveField(
            model_name='selling_cart',
            name='title',
        ),
        migrations.RemoveField(
            model_name='shopping_cart',
            name='author',
        ),
        migrations.RemoveField(
            model_name='shopping_cart',
            name='image',
        ),
        migrations.RemoveField(
            model_name='shopping_cart',
            name='isbn',
        ),
        migrations.RemoveField(
            model_name='shopping_cart',
            name='price',
        ),
        migrations.RemoveField(
            model_name='shopping_cart',
            name='title',
        ),
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AddField(
            model_name='selling_cart',
            name='book',
            field=models.ManyToManyField(to='mysite.Book'),
        ),
        migrations.AddField(
            model_name='selling_cart',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mysite.User'),
        ),
        migrations.AddField(
            model_name='shopping_cart',
            name='book',
            field=models.ManyToManyField(to='mysite.Book'),
        ),
        migrations.AddField(
            model_name='shopping_cart',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mysite.User'),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='order',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.Shopping_Cart'),
        ),
    ]
