# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-02-25 16:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0009_auto_20180225_1643'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selling_cart',
            name='id',
        ),
        migrations.RemoveField(
            model_name='shopping_cart',
            name='id',
        ),
        migrations.AddField(
            model_name='selling_cart',
            name='cart',
            field=models.IntegerField(default=2, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='shopping_cart',
            name='cart',
            field=models.IntegerField(default=2, primary_key=True, serialize=False),
        ),
    ]
