# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-02-27 13:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0011_auto_20180226_1610'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selling_cart',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='shopping_cart',
            name='cart',
        ),
        migrations.AlterField(
            model_name='selling_cart',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='mysite.User'),
        ),
        migrations.AlterField(
            model_name='shopping_cart',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='mysite.User'),
        ),
    ]
